### ISSUE TITLE
[Suggestion] List dependencies

### ISSUE THREAD

**Issue by onlyreportingissues** [cosmic-utils/observatory#22]
Can't compile it on Fedora, something is missing. Would be cool, if you could list the required dependencies so I can build it successfully. 🙏

**Comment by Adam-Cosner** [comment]
Are you building from source or trying to install with the deb?

**Comment by Adam-Cosner** [comment]
I just published an rpm package in the releases section, check if that builds and installs

**Comment by onlyreportingissues** [comment]
> I just published an rpm package in the releases section, check if that builds and installs

Didn't find the rpm in the releases section, but I managed to install it:

The packages that were missing on my Fedora install: 

- mesa-libgbm-devel
- mesa-libEGL-devel
- libdrm-devel
- protobuf-devel

The build still failed though, had to make a copy of the content of the folder (that I git clone from your repo) and put it inside a new folder called "src". After this the building process was successful.
